# https://github.com/craigcitro/r-travis/blob/master/README.md
# Adding .travis.yml to your .Rbuildignore.
# Modifying .travis.yml to list any packages that must be installed from github (instead of CRAN).
# Turn on travis for your project.
# Add a travis "build status" shield to your README file.

# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
install:
  - ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: ttmmghmm+travis.yml@gmail.com